### ISSUE TITLE
Change the default boot partition to MMC1

### ISSUE THREAD

**Issue by Pugemonster** [Pugemon/OPi-R1-Plus-LTS-OpenWrt#3]
Due to the default usage of MMC0, OPi is unable to reboot properly after resetting the settings or updating through LuCi.

**Comment by Pugemon** [comment]
Not needed #[Fix](https://github.com/Pugemon/openwrt/commit/4bfc28da3584a030aa2fc313e9e25c325695d229)

**Comment by Pugemonster** [comment]
Not needed #[Fix](https://github.com/Pugemon/openwrt/commit/4bfc28da3584a030aa2fc313e9e25c325695d229)
